### ISSUE TITLE
Android Implementation

### ISSUE THREAD

**Issue by mrousavy** [mrousavy/react-native-screen-corner-radius#1]
Unfortunately I haven't really found a way to get the corner radii of the physical screen on Android yet. I've found the [`isScreenRound()`](https://developer.android.com/reference/android/content/res/Configuration#isScreenRound()) function, but that doesn't give me an exact point value of the radius.

Any help appreciated!

**Comment by ajacquierbret** [comment]
Hey ! You've done some really nice stuff !

I don't know how you could get the corner radius of Android devices but maybe you could include the `isScreenRound()` function, it'll at least give us the ability to not set any border radius on an app's element if the device screen isn't rounded at all.

I think the best solution we have now in order to detect device's screen corner radius is to check the actual device in use, and retrieve the screen corner radius from a list of devices specs, if such a list already exists.

**Comment by ajacquierbret** [comment]
My bad, didn't see that you already published a library for doing so :

https://github.com/mrousavy/react-native-is-rounded-screen/tree/master/android

**Comment by mrousavy** [comment]
Hi @ajacquierbret! The library you linked does not work for android (yet). If you take a look at the source code, I wasn't sure how to statically retrieve the window insets.

As for the `isScreenRound()` function - I think that's only for actually round screens like watches.

**Comment by ajacquierbret** [comment]
Oh I see, so there's no way we could retrieve this information yet ?

**Comment by mrousavy** [comment]
Unfortunately not. I didn't have any time for this lately, but if you're interested in a little bit of android development, it shouldn't be too difficult.

**Comment by ajacquierbret** [comment]
For shure, I think designing components with these rounded corners in mind is quite important, so I'll dig into this issue if I can free up some time. Thanks for your explanations and feedbacks !

**Comment by yfunk** [comment]
Android 12 introduces [`RoundedCorner`](https://developer.android.com/reference/android/view/RoundedCorner) and  [`WindowInsets.getRoundedCorner(int position)`](https://developer.android.com/reference/android/view/WindowInsets?hl=en#getRoundedCorner(int)), which could be used to implement this.

**Comment by mrousavy** [comment]
Nice! We can use that 👍

**Comment by MikePodgorniy** [comment]
@mrousavy @yfunk Any updates?

**Comment by MikePodgorniy** [comment]
@mrousavy Hello, I don't know how to create identical API for Android and iOS. Is it posible? Or I need to change ts api to use callbacks/promises for iOS to? like:
```
export const ScreenCornerRadius: number =
  NativeModules.ScreenCornerRadius.cornerRadius;

/**
 * `true` if the screen has rounded corners, `false` otherwise.
 */
export const IsScreenRounded = ScreenCornerRadius > 0;

/**
*  async cornerRadius for iOS and Android
*/
export async function getCornerRadius() {
  if (Platform.OS === 'android') {
   return await NativeModules.ScreenCornerRadius.getCornerRadius();
  } else {
   return NativeModules.ScreenCornerRadius.cornerRadius;
  }
}
```

```
@RequiresApi(Build.VERSION_CODES.S)
    @ReactMethod
    fun getCornerRadius(promise: Promise) {
        rootView = currentActivity?.window?.decorView?.findViewById(android.R.id.content)
        if (rootView != null) {
            val corner = rootView?.rootWindowInsets?.getRoundedCorner(RoundedCorner.POSITION_TOP_LEFT)
            promise.resolve(corner?.radius)
        } else {
            promise.reject("VIEW_NOT_FOUND", "Could not find the root view")
        }
    }
```

**Comment by mrousavy** [comment]
Hey, no on Android it can also be either a constant or a `@ReactMethod(isBlockingSynchronous = true)` that returns a number

**Comment by MikePodgorniy** [comment]
@mrousavy should call results be cached for android or how to make it available as constant (I can't find this information on docs)? 

> At the moment, we do not recommend this, since calling methods synchronously can have strong performance penalties and introduce threading-related bugs to your native modules. Additionally, please note that if you choose to enable isBlockingSynchronousMethod, your app can no longer use the Google Chrome debugger. This is because synchronous methods require the JS VM to share memory with the app. For the Google Chrome debugger, React Native runs inside the JS VM in Google Chrome, and communicates asynchronously with the mobile devices via WebSockets.

**Comment by mrousavy** [comment]
The recommendation is worded wrong imo. For this, sync methods are perfect.

**Comment by MikePodgorniy** [comment]
@mrousavy  OK? (with isBlockingSynchronousMethod)
`export const ScreenCornerRadius: number = Platform.OS == 'andoid' ?  NativeModules.ScreenCornerRadius.getCornerRadius() :  NativeModules.ScreenCornerRadius.cornerRadius;
`

**Comment by MikePodgorniy** [comment]
@mrousavy #5 PR is ready

**Comment by mrousavy** [comment]
sure I'll take a look in a few hours! thanks
