### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.ScreenCornerRadius.cornerRadius')

### ISSUE THREAD

**Issue by BerkeAras** [mrousavy/react-native-screen-corner-radius#3]
Getting TypeError: null is not an object (evaluating '_reactNative.NativeModules.ScreenCornerRadius.cornerRadius') when using with expo. Used the example in the repository.

**Comment by mrousavy** [comment]
It's a native module, you cannot use it with Expo Go. Use EAS
